In [1]:
import pandas as pd
import numpy as np

In [2]:
df5=pd.read_csv("../data/raw/olist_products_dataset.csv")
df6=pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
df8=pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

In [3]:
print("Before:", df8.shape)

df8_clean = df8.drop_duplicates()

print("After:", df8_clean.shape)
print("Duplicates Removed:", df8.shape[0] - df8_clean.shape[0])

Before: (1000163, 5)
After: (738332, 5)
Duplicates Removed: 261831

In [4]:
df8_clean.duplicated().sum()

np.int64(0)

In [6]:
df8_clean.to_csv("../data/processed/geolocation_clean.csv", index=False)

# Geolocation Cleaning

### Problem
The geolocation dataset contained duplicate records.

### Solution
Removed duplicate rows using pandas `drop_duplicates()`.

### Result
Created a cleaned dataset with only unique records for downstream analysis.

In [7]:
df5.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [9]:
df5[df5.isnull().any(axis=1)]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [10]:
df5[df5.isnull().any(axis=1)].shape

(611, 9)

In [11]:
df5_clean = df5.copy()

df5_clean["product_category_name"] = df5_clean["product_category_name"].fillna("Unknown")

numeric_cols = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in numeric_cols:
    df5_clean[col] = df5_clean[col].fillna(df5_clean[col].median())

In [12]:
df5_clean.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [13]:
df5_clean.to_csv("../data/processed/products_clean.csv", index=False)

# Products Dataset Cleaning

## Issues Identified
- Missing values in product category and product attributes.

## Cleaning Performed
- Filled missing product categories with **"Unknown"**.
- Filled missing numeric attributes using the **median**, which is robust to outliers.

## Output
- Saved cleaned dataset as `products_clean.csv`.

In [14]:
df6.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [15]:
df6[df6.isnull().any(axis=1)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [16]:
df6_clean = df6.copy()

df6_clean["review_comment_title"] = df6_clean["review_comment_title"].fillna("No Title")
df6_clean["review_comment_message"] = df6_clean["review_comment_message"].fillna("No Comment")

In [17]:
df6_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [18]:
df6_clean.to_csv("../data/processed/reviews_clean.csv", index=False)

# Reviews Dataset Cleaning

## Issues Identified
- Missing values in review title and review message.

## Cleaning Performed
- Filled missing review titles with **"No Title"**.
- Filled missing review messages with **"No Comment"**.

## Output
- Saved cleaned dataset as `reviews_clean.csv`.